export const EducationList = [
	{
		title: 'UCLA',
		src: require('./imgs/1200px-UCLA_Bruins_script.svg.png'),
		cName: 'Education-IMG',
		cH3Name: 'Education-Title-Style',
		h3Title: 'Full Stack Software Development Bootcamp',
		cPName: 'Education-Date-Style',
		timeEdu: 'March 2020 to September 2020',
	},
	{
		title: 'GeneralAssembly',
		src: require('./imgs/GA.png'),
		cName: 'Education-IMG',
		cH3Name: 'Education-Title-Style',
		h3Title: 'Data Analytics',
		cPName: 'Education-Date-Style',
		timeEdu: 'December 2018 to March 2019',
	},
	{
		title: 'CalTech',
		src: require('./imgs/CalTech.png'),
		cName: 'Education-IMG',
		cH3Name: 'Education-Title-Style',
		h3Title: 'Project Management Professional (PMP) Certificate',
		cPName: 'Education-Date-Style',
		timeEdu: 'Summer 2017',
	},
	{
		title: 'ChapmanUniversity',
		src: require('./imgs/cu-master-brand-2018.png'),
		cName: 'Education-IMG',
		cH3Name: 'Education-Title-Style',
		h3Title: 'Sociology, B.A.',
		cPName: 'Education-Date-Style',
		timeEdu: 'September 2007 to May 2011',
	},
];
