export const FeaturedProjects = [
	{
		id: 0,
		title: 'Dubsado Scheduler',
		src: require('./imgs/FeaturedWorkContent/DubSchedulertNail.jpg'),
		url: '#FP1',
		cName: 'Work-IMG',
		tNailName: 'Dubsado Scheduler',
		tNailClass: 'Tnail-CSS',
		modalTitle: 'Dubsado Scheduler',
		modalGif: require('./imgs/FeaturedWorkContent/DubSchedulerGif.gif'),
		modalDesc: 'Developed a new scheduling feature for Los Angeles based SAAS start-up Dubsado. Built on top of FullCalendar js, allows users to schedule new appointments and receive an appointment confirmation email.',
		modalBuiltWith: 'Javascript, jQuery, Node.js, Express, Handlebars, MySQL, Microsoft Azure, HTML, CSS, uiKit, FullCalendar JS',
		githubLink: '',
		deployedLink: '',
		privateRepo: true,
		delployed: false,
	},
	{
		id: 1,
		title: 'FP2',
		src: require('./imgs/FeaturedWorkContent/TIOtNail.jpg'),
		url: '#FP2',
		cName: 'Work-IMG',
		tNailName: 'Tuition.io One Pager',
		tNailClass: 'Tnail-CSS',
		modalTitle: 'Tuition.io One Pager Application',
		modalGif: require('./imgs/FeaturedWorkContent/TIOgif1.gif'),
		modalDesc: 'Developed an information repository platform for Los Angeles start-up Tuition.io that consolidates partner program information into a one stop access application. The One Pager Application increase efficiency for the Tuition.io Customer Support Team when accessing information.',
		modalBuiltWith: 'Javascript, jQuery, Node.js, Express, Handlebars, MySQL, Microsoft Azure, HTML, CSS, uiKit, FullCalendar JS',
		githubLink: '',
		deployedLink: '',
		privateRepo: true,
		delployed: false,
	},
	{
		id: 2,
		title: 'FP3',
		src: require('./imgs/FeaturedWorkContent/EmployeeCLItNail.jpg'),
		url: '#FP3',
		cName: 'Work-IMG',
		tNailName: 'Employee Tracker CLI',
		tNailClass: 'Tnail-CSS',
		modalTitle: 'Employee Tracker CLI',
		modalGif: require('./imgs/FeaturedWorkContent/EmployeeManagerMySQLGif.gif'),
		modalDesc: 'Command Line Interface built in Node.js with MySQL CRUD operations that provides employee information. Allows user to view, add, update, and delete employee information.',
		modalBuiltWith: 'Javascript, Node.js, MySQL, Inquirer, Chalk',
		githubLink: 'https://github.com/JeffQuit/MySQL---Employee-Tracker-CLI',
		deployedLink: '',
		privateRepo: false,
		delployed: false,
	},
];
